# Generated by Django 3.0.8 on 2020-07-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Done')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasklist',
            field=models.IntegerField(choices=[(0, 'Next Action'), (1, 'Someday / Maybe'), (2, 'Support Material')], default=0),
        ),
    ]
