# Generated by Django 3.0.8 on 2020-07-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contexts',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.Context'),
        ),
    ]
