# Generated by Django 3.0.8 on 2020-07-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_contexts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['creation_datetime']},
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
