# Generated by Django 3.0.8 on 2020-07-28 05:40

from django.db import migrations

def set_ready_time(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    for task in Task.objects.all():
        task.ready_datetime = task.creation_datetime
        task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200728_0739'),
    ]

    operations = [
        migrations.RunPython(set_ready_time),
    ]
