# Generated by Django 3.0.8 on 2020-08-03 18:09

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200728_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_order',
            field=models.IntegerField(default=1),
        ),
    ]
