# Generated by Django 3.0.8 on 2021-02-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20210113_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasklist',
            field=models.IntegerField(choices=[(0, 'Next Action'), (1, 'Someday / Maybe'), (2, 'Support Material'), (2, 'Not This Week')], default=0),
        ),
    ]
