# Generated by Django 3.0.8 on 2021-03-20 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20210215_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Done'), (2, 'Blocked')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasklist',
            field=models.IntegerField(choices=[(0, 'Next Action'), (1, 'Someday / Maybe'), (2, 'Support Material'), (3, 'Not This Week')], default=0),
        ),
    ]
