# Generated by Django 3.1.7 on 2021-03-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20210320_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='repeat',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Daily'), (2, 'Daily (BD)'), (7, 'Weekly'), (15, 'Biweekly'), (30, 'Monthly'), (60, 'Bimonthly'), (90, 'Quaterly'), (180, 'Semiannually'), (360, 'Yearly')], default=0),
        ),
    ]
