# Generated by Django 3.1.7 on 2021-08-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20210331_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(3, '3 Urgent'), (2, '2 Commitment'), (1, '1 Above normal'), (0, '0 Normal'), (-1, '-1 Below normal')], default=0),
        ),
    ]
