# Generated by Django 3.1.7 on 2022-03-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20211011_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.folder'),
        ),
    ]
