# Generated by Django 3.1.7 on 2024-07-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_task_time_constrained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_constrained',
        ),
    ]
