# Generated by Django 3.1.7 on 2024-10-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_remove_task_time_constrained'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.IntegerField(choices=[(1, 'OPEN'), (0, 'CLOSED')], default=1),
        ),
    ]
