# Generated by Django 3.1.7 on 2024-11-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_auto_20241126_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
