# Generated by Django 3.1.7 on 2024-11-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_auto_20241127_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='references',
        ),
        migrations.AddField(
            model_name='goal',
            name='references',
            field=models.TextField(blank=True),
        ),
    ]
