# Generated by Django 3.1.7 on 2025-07-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_task_planned_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='goal_position',
            field=models.IntegerField(default=0),
        ),
    ]
