# Generated by Django 3.1.7 on 2025-07-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_holidayperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayperiod',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='holidayperiod',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
    ]
