# Generated by Django 6.0.1 on 2026-03-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0038_task_flexible_due_date_alter_assignee_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="roadmap",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="milestone",
            field=models.BooleanField(default=False),
        ),
    ]
