# Generated by Django 6.0.1 on 2026-04-30 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0039_goal_roadmap_task_milestone"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tracked_time_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cumulative time logged from the task timer (stop).",
            ),
        ),
        migrations.CreateModel(
            name="TaskTimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seconds", models.PositiveIntegerField()),
                ("work_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
