# Generated by Django 6.0.1 on 2026-04-30 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0040_task_tracked_time_and_time_entries"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskTimerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accumulated_seconds", models.PositiveIntegerField(default=0)),
                ("segment_started_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timer_session",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task timer session",
            },
        ),
    ]
