# Generated by Django 6.0.1 on 2026-09-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_task_timer_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deliverable_name',
            field=models.CharField(blank=True, help_text='Name/description of the deliverable produced by this task, if any. Leave blank if this task has no deliverable.', max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(3, 'Blocker'), (2, 'Critical'), (1, 'Major'), (0, 'Normal'), (-1, 'Minor')], default=0),
        ),
    ]
