# Generated by Django 6.0.1 on 2026-10-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0042_task_deliverable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day_position',
            field=models.IntegerField(default=0, help_text="Tiebreaker used only among a user's tasks that share the same due_date and priority in the main task-list ordering (e.g. the 'move to end of day' action). Unrelated to goal_position."),
        ),
        migrations.AlterField(
            model_name='task',
            name='goal_position',
            field=models.IntegerField(default=0, help_text="Manual rank of this task within its goal's own task list (1..N, reassigned wholesale whenever the goal is reordered). Meaningless for tasks without a goal."),
        ),
    ]
